Repository amorilla42/cub3d, pull requests merged in 2023-07, with the labels that each got.

#8 Wolfenstein 3D textures added
  assets/textures/blue_stone.xpm
  assets/textures/color_stone.xpm
  assets/textures/eagle.xpm
  assets/textures/grey_stone.xpm
  assets/textures/mossy.xpm
  assets/textures/purple_stone.xpm
  assets/textures/red_brick.xpm
  assets/textures/wood.xpm
Labels: MLX

#11 10 hacer mapas de ejemplo
  assets/maps/mapa1.cub
  assets/textures/blue_stone.xpm
  assets/textures/color_stone.xpm
  assets/textures/eagle.xpm
  assets/textures/grey_stone.xpm
  assets/textures/mossy.xpm
  assets/textures/purple_stone.xpm
  assets/textures/red_brick.xpm
  assets/textures/wood.xpm
  src/parser/parsemap.c
Labels: enhancement, parser

#16 fix: get_next_line
  libs/get_next_line/get_next_line.c
  libs/get_next_line/get_next_line.h
  libs/get_next_line/get_next_line_utils.c
Labels: bug

#17 9 gestion de ventana
  .gitignore
  README.md
  src/cub3d.c
  src/cub3d.h
  src/free.c
Labels: enhancement, MLX

#15 MLX42 documentation
  MLX42_FUNCTIONS_GUIDE.md
Labels: documentation, MLX
