Repository amorilla42/cub3d, pull requests merged in 2023-08, with the labels that each got.

#21 compila, reduccion de funciones a la mitad de parseo
  .gitignore
  src/parser/parsemap.c
Labels: enhancement

#26 19 documentar struct tdata y substructuras
  cub3d.h
Labels: documentation

#28 24 guardar el mapa en la estructura
  Makefile
  assets/maps/map1.cub
  assets/maps/map2.cub
  assets/maps/mapa1.cub
  assets/textures/blue_stone.xpm
  assets/textures/bluestone.png
  assets/textures/color_stone.xpm
  assets/textures/colorstone.png
  assets/textures/eagle.png
  assets/textures/eagle.xpm
  assets/textures/grey_stone.xpm
  assets/textures/greystone.png
  assets/textures/mossy.png
  assets/textures/mossy.xpm
  assets/textures/purple_stone.xpm
  assets/textures/purplestone.png
  assets/textures/red_brick.xpm
  assets/textures/redbrick.png
  assets/textures/wood.png
  assets/textures/wood.xpm
  cub3d.c
  cub3d.h
  libs/get_next_line/get_next_line.c
  libs/get_next_line/get_next_line.h
  libs/get_next_line/get_next_line_utils.c
  src/cub3d.c
  src/cub3d.h
  src/free.c
  src/init_data.c
  src/movement/get_player_orientation.c
  src/movement/move_player.c
  src/movement/rotate_player.c
  src/parser/colors.c
  src/parser/colors_utils.c
  src/parser/load_textures.c
  src/parser/parsemap.c
  src/parser/save_map.c
  src/render/raycasting.c
  src/render/textures.c
Labels: enhancement, parser, MLX

#31 add collisions and some norminette
  Makefile
  src/cub3d.c
  src/cub3d.h
  src/free.c
  src/movement/collisions.c
  src/movement/move_player.c
  src/parser/colors.c
  src/parser/colors_utils.c
  src/parser/load_textures.c
  src/parser/parsemap.c
  src/render/raycasting.c
Labels: enhancement

#34 add colors number atoi checker
  src/cub3d.h
  src/parser/colors.c
  src/parser/colors_utils.c
Labels: bug

#42 41 arreglar movimiento bloqueado
  src/movement/collisions.c
  src/movement/move_player.c
Labels: bug

#33 fix makefile
  Makefile
Labels: bug
